services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12346
      POSTGRES_DB: tpfinal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:3000/api
    container_name: frontend_app
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data: